default:
  image: 
    name: hashicorp/terraform:1.3.7
    entrypoint: [""]


variables:
  TF_IN_AUTOMATION: "true"
  TF_CLI_ARGS_init: "-input=false"

  OPERATION:
    value: "plan"
    description: "Select operation: validate, plan, apply, or destroy"
    options:
      - "validate"
      - "plan"
      - "apply"
      - "destroy"

.tf-init: &tf-init
  before_script:
    - terraform --version
    - terraform init -input=false

stages:
  - terraform-validate
  - terraform-plan
  - terraform-apply
  - terraform-destroy

terraform-validate:
  stage: terraform-validate
  <<: *tf-init
  script:
    - terraform fmt -check -recursive
    - terraform fmt
    - terraform validate
  rules:
    - when: always

terraform-plan:
  stage: terraform-plan
  <<: *tf-init
  script:
    - terraform plan -input=false -out=tfplan
  artifacts:
    name: "tfplan-${CI_COMMIT_SHORT_SHA}"
    paths:
      - tfplan
    expire_in: 7 days
  rules:
    - when: always
  needs:
    - terraform-validate

terraform-apply:
  stage: terraform-apply
  <<: *tf-init
  script:
    - terraform plan -input=false -out=tfplan
    - terraform apply -input=false -auto-approve tfplan
  rules:
    - when: manual
  needs:
    - terraform-plan

terraform-destroy-plan:
  stage: terraform-destroy
  <<: *tf-init
  script:
    - terraform plan -destroy -out=destroyplan
  artifacts:
    paths:
      - destroyplan
  rules:
    - when: manual
  needs:
    - terraform-validate

terraform-destroy:
  stage: terraform-destroy
  <<: *tf-init
  script:
    - terraform apply -auto-approve destroyplan
  rules:
    - when: manual
  needs:
    - terraform-destroy-plan




  




