cluster_name       = "nav-eks-demo"
kubernetes_version = "1.32"
vpc_cidr_block     = "10.0.0.0/16"
subnet_cidr_blocks = ["10.0.1.0/24", "10.0.2.0/24"]
availability_zones = ["us-east-1a", "us-east-1b"]
region             = "us-east-1"
tag                = "eks"
instance_type      = "t2.micro"
min_size           = "1"
max_size           = "3"
desired_size       = "2"
